/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ExamplePageImport } from './routes/ExamplePage'
import { Route as TaxiIndexImport } from './routes/taxi/index'
import { Route as TaxiRutaImport } from './routes/taxi/ruta'

// Create Virtual Routes

const SobreLazyImport = createFileRoute('/sobre')()
const RegistroLazyImport = createFileRoute('/registro')()
const LoginLazyImport = createFileRoute('/login')()
const ContactoLazyImport = createFileRoute('/contacto')()
const AyudaLazyImport = createFileRoute('/ayuda')()
const RTMapLazyImport = createFileRoute('/RTMap')()
const IndexLazyImport = createFileRoute('/')()
const ViajesIndexLazyImport = createFileRoute('/viajes/')()
const ValoracionIndexLazyImport = createFileRoute('/valoracion/')()
const ReservasIndexLazyImport = createFileRoute('/reservas/')()
const ViajesCodigoViajeLazyImport = createFileRoute('/viajes/$codigoViaje')()
const ValoracionCreateLazyImport = createFileRoute('/valoracion/create')()
const ReservasCreateLazyImport = createFileRoute('/reservas/create')()
const ReservasCodigoReservaLazyImport = createFileRoute(
  '/reservas/$codigoReserva',
)()
const AdminTaxisLazyImport = createFileRoute('/admin/taxis')()
const AdminDashboardLazyImport = createFileRoute('/admin/dashboard')()
const AdminCreateBookingLazyImport = createFileRoute('/admin/create-booking')()
const AdminConductoresLazyImport = createFileRoute('/admin/conductores')()
const AdminReservasIndexLazyImport = createFileRoute('/admin/reservas/')()
const AdminReservasCodigoReservaAdminLazyImport = createFileRoute(
  '/admin/reservas/$codigoReservaAdmin',
)()
const AdminConductorRutLazyImport = createFileRoute('/admin/conductor/$rut')()

// Create/Update Routes

const SobreLazyRoute = SobreLazyImport.update({
  path: '/sobre',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/sobre.lazy').then((d) => d.Route))

const RegistroLazyRoute = RegistroLazyImport.update({
  path: '/registro',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/registro.lazy').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const ContactoLazyRoute = ContactoLazyImport.update({
  path: '/contacto',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/contacto.lazy').then((d) => d.Route))

const AyudaLazyRoute = AyudaLazyImport.update({
  path: '/ayuda',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/ayuda.lazy').then((d) => d.Route))

const RTMapLazyRoute = RTMapLazyImport.update({
  path: '/RTMap',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/RTMap.lazy').then((d) => d.Route))

const ExamplePageRoute = ExamplePageImport.update({
  path: '/ExamplePage',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ViajesIndexLazyRoute = ViajesIndexLazyImport.update({
  path: '/viajes/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/viajes/index.lazy').then((d) => d.Route))

const ValoracionIndexLazyRoute = ValoracionIndexLazyImport.update({
  path: '/valoracion/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/valoracion/index.lazy').then((d) => d.Route),
)

const ReservasIndexLazyRoute = ReservasIndexLazyImport.update({
  path: '/reservas/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/reservas/index.lazy').then((d) => d.Route),
)

const TaxiIndexRoute = TaxiIndexImport.update({
  path: '/taxi/',
  getParentRoute: () => rootRoute,
} as any)

const ViajesCodigoViajeLazyRoute = ViajesCodigoViajeLazyImport.update({
  path: '/viajes/$codigoViaje',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/viajes/$codigoViaje.lazy').then((d) => d.Route),
)

const ValoracionCreateLazyRoute = ValoracionCreateLazyImport.update({
  path: '/valoracion/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/valoracion/create.lazy').then((d) => d.Route),
)

const ReservasCreateLazyRoute = ReservasCreateLazyImport.update({
  path: '/reservas/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/reservas/create.lazy').then((d) => d.Route),
)

const ReservasCodigoReservaLazyRoute = ReservasCodigoReservaLazyImport.update({
  path: '/reservas/$codigoReserva',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/reservas/$codigoReserva.lazy').then((d) => d.Route),
)

const AdminTaxisLazyRoute = AdminTaxisLazyImport.update({
  path: '/admin/taxis',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/admin/taxis.lazy').then((d) => d.Route))

const AdminDashboardLazyRoute = AdminDashboardLazyImport.update({
  path: '/admin/dashboard',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/dashboard.lazy').then((d) => d.Route),
)

const AdminCreateBookingLazyRoute = AdminCreateBookingLazyImport.update({
  path: '/admin/create-booking',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/create-booking.lazy').then((d) => d.Route),
)

const AdminConductoresLazyRoute = AdminConductoresLazyImport.update({
  path: '/admin/conductores',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/conductores.lazy').then((d) => d.Route),
)

const TaxiRutaRoute = TaxiRutaImport.update({
  path: '/taxi/ruta',
  getParentRoute: () => rootRoute,
} as any)

const AdminReservasIndexLazyRoute = AdminReservasIndexLazyImport.update({
  path: '/admin/reservas/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/reservas/index.lazy').then((d) => d.Route),
)

const AdminReservasCodigoReservaAdminLazyRoute =
  AdminReservasCodigoReservaAdminLazyImport.update({
    path: '/admin/reservas/$codigoReservaAdmin',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/admin/reservas/$codigoReservaAdmin.lazy').then(
      (d) => d.Route,
    ),
  )

const AdminConductorRutLazyRoute = AdminConductorRutLazyImport.update({
  path: '/admin/conductor/$rut',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/admin/conductor/$rut.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/ExamplePage': {
      id: '/ExamplePage'
      path: '/ExamplePage'
      fullPath: '/ExamplePage'
      preLoaderRoute: typeof ExamplePageImport
      parentRoute: typeof rootRoute
    }
    '/RTMap': {
      id: '/RTMap'
      path: '/RTMap'
      fullPath: '/RTMap'
      preLoaderRoute: typeof RTMapLazyImport
      parentRoute: typeof rootRoute
    }
    '/ayuda': {
      id: '/ayuda'
      path: '/ayuda'
      fullPath: '/ayuda'
      preLoaderRoute: typeof AyudaLazyImport
      parentRoute: typeof rootRoute
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroLazyImport
      parentRoute: typeof rootRoute
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreLazyImport
      parentRoute: typeof rootRoute
    }
    '/taxi/ruta': {
      id: '/taxi/ruta'
      path: '/taxi/ruta'
      fullPath: '/taxi/ruta'
      preLoaderRoute: typeof TaxiRutaImport
      parentRoute: typeof rootRoute
    }
    '/admin/conductores': {
      id: '/admin/conductores'
      path: '/admin/conductores'
      fullPath: '/admin/conductores'
      preLoaderRoute: typeof AdminConductoresLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/create-booking': {
      id: '/admin/create-booking'
      path: '/admin/create-booking'
      fullPath: '/admin/create-booking'
      preLoaderRoute: typeof AdminCreateBookingLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/taxis': {
      id: '/admin/taxis'
      path: '/admin/taxis'
      fullPath: '/admin/taxis'
      preLoaderRoute: typeof AdminTaxisLazyImport
      parentRoute: typeof rootRoute
    }
    '/reservas/$codigoReserva': {
      id: '/reservas/$codigoReserva'
      path: '/reservas/$codigoReserva'
      fullPath: '/reservas/$codigoReserva'
      preLoaderRoute: typeof ReservasCodigoReservaLazyImport
      parentRoute: typeof rootRoute
    }
    '/reservas/create': {
      id: '/reservas/create'
      path: '/reservas/create'
      fullPath: '/reservas/create'
      preLoaderRoute: typeof ReservasCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/valoracion/create': {
      id: '/valoracion/create'
      path: '/valoracion/create'
      fullPath: '/valoracion/create'
      preLoaderRoute: typeof ValoracionCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/viajes/$codigoViaje': {
      id: '/viajes/$codigoViaje'
      path: '/viajes/$codigoViaje'
      fullPath: '/viajes/$codigoViaje'
      preLoaderRoute: typeof ViajesCodigoViajeLazyImport
      parentRoute: typeof rootRoute
    }
    '/taxi/': {
      id: '/taxi/'
      path: '/taxi'
      fullPath: '/taxi'
      preLoaderRoute: typeof TaxiIndexImport
      parentRoute: typeof rootRoute
    }
    '/reservas/': {
      id: '/reservas/'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof ReservasIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/valoracion/': {
      id: '/valoracion/'
      path: '/valoracion'
      fullPath: '/valoracion'
      preLoaderRoute: typeof ValoracionIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/viajes/': {
      id: '/viajes/'
      path: '/viajes'
      fullPath: '/viajes'
      preLoaderRoute: typeof ViajesIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/conductor/$rut': {
      id: '/admin/conductor/$rut'
      path: '/admin/conductor/$rut'
      fullPath: '/admin/conductor/$rut'
      preLoaderRoute: typeof AdminConductorRutLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/reservas/$codigoReservaAdmin': {
      id: '/admin/reservas/$codigoReservaAdmin'
      path: '/admin/reservas/$codigoReservaAdmin'
      fullPath: '/admin/reservas/$codigoReservaAdmin'
      preLoaderRoute: typeof AdminReservasCodigoReservaAdminLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/reservas/': {
      id: '/admin/reservas/'
      path: '/admin/reservas'
      fullPath: '/admin/reservas'
      preLoaderRoute: typeof AdminReservasIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/ExamplePage': typeof ExamplePageRoute
  '/RTMap': typeof RTMapLazyRoute
  '/ayuda': typeof AyudaLazyRoute
  '/contacto': typeof ContactoLazyRoute
  '/login': typeof LoginLazyRoute
  '/registro': typeof RegistroLazyRoute
  '/sobre': typeof SobreLazyRoute
  '/taxi/ruta': typeof TaxiRutaRoute
  '/admin/conductores': typeof AdminConductoresLazyRoute
  '/admin/create-booking': typeof AdminCreateBookingLazyRoute
  '/admin/dashboard': typeof AdminDashboardLazyRoute
  '/admin/taxis': typeof AdminTaxisLazyRoute
  '/reservas/$codigoReserva': typeof ReservasCodigoReservaLazyRoute
  '/reservas/create': typeof ReservasCreateLazyRoute
  '/valoracion/create': typeof ValoracionCreateLazyRoute
  '/viajes/$codigoViaje': typeof ViajesCodigoViajeLazyRoute
  '/taxi': typeof TaxiIndexRoute
  '/reservas': typeof ReservasIndexLazyRoute
  '/valoracion': typeof ValoracionIndexLazyRoute
  '/viajes': typeof ViajesIndexLazyRoute
  '/admin/conductor/$rut': typeof AdminConductorRutLazyRoute
  '/admin/reservas/$codigoReservaAdmin': typeof AdminReservasCodigoReservaAdminLazyRoute
  '/admin/reservas': typeof AdminReservasIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/ExamplePage': typeof ExamplePageRoute
  '/RTMap': typeof RTMapLazyRoute
  '/ayuda': typeof AyudaLazyRoute
  '/contacto': typeof ContactoLazyRoute
  '/login': typeof LoginLazyRoute
  '/registro': typeof RegistroLazyRoute
  '/sobre': typeof SobreLazyRoute
  '/taxi/ruta': typeof TaxiRutaRoute
  '/admin/conductores': typeof AdminConductoresLazyRoute
  '/admin/create-booking': typeof AdminCreateBookingLazyRoute
  '/admin/dashboard': typeof AdminDashboardLazyRoute
  '/admin/taxis': typeof AdminTaxisLazyRoute
  '/reservas/$codigoReserva': typeof ReservasCodigoReservaLazyRoute
  '/reservas/create': typeof ReservasCreateLazyRoute
  '/valoracion/create': typeof ValoracionCreateLazyRoute
  '/viajes/$codigoViaje': typeof ViajesCodigoViajeLazyRoute
  '/taxi': typeof TaxiIndexRoute
  '/reservas': typeof ReservasIndexLazyRoute
  '/valoracion': typeof ValoracionIndexLazyRoute
  '/viajes': typeof ViajesIndexLazyRoute
  '/admin/conductor/$rut': typeof AdminConductorRutLazyRoute
  '/admin/reservas/$codigoReservaAdmin': typeof AdminReservasCodigoReservaAdminLazyRoute
  '/admin/reservas': typeof AdminReservasIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/ExamplePage': typeof ExamplePageRoute
  '/RTMap': typeof RTMapLazyRoute
  '/ayuda': typeof AyudaLazyRoute
  '/contacto': typeof ContactoLazyRoute
  '/login': typeof LoginLazyRoute
  '/registro': typeof RegistroLazyRoute
  '/sobre': typeof SobreLazyRoute
  '/taxi/ruta': typeof TaxiRutaRoute
  '/admin/conductores': typeof AdminConductoresLazyRoute
  '/admin/create-booking': typeof AdminCreateBookingLazyRoute
  '/admin/dashboard': typeof AdminDashboardLazyRoute
  '/admin/taxis': typeof AdminTaxisLazyRoute
  '/reservas/$codigoReserva': typeof ReservasCodigoReservaLazyRoute
  '/reservas/create': typeof ReservasCreateLazyRoute
  '/valoracion/create': typeof ValoracionCreateLazyRoute
  '/viajes/$codigoViaje': typeof ViajesCodigoViajeLazyRoute
  '/taxi/': typeof TaxiIndexRoute
  '/reservas/': typeof ReservasIndexLazyRoute
  '/valoracion/': typeof ValoracionIndexLazyRoute
  '/viajes/': typeof ViajesIndexLazyRoute
  '/admin/conductor/$rut': typeof AdminConductorRutLazyRoute
  '/admin/reservas/$codigoReservaAdmin': typeof AdminReservasCodigoReservaAdminLazyRoute
  '/admin/reservas/': typeof AdminReservasIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ExamplePage'
    | '/RTMap'
    | '/ayuda'
    | '/contacto'
    | '/login'
    | '/registro'
    | '/sobre'
    | '/taxi/ruta'
    | '/admin/conductores'
    | '/admin/create-booking'
    | '/admin/dashboard'
    | '/admin/taxis'
    | '/reservas/$codigoReserva'
    | '/reservas/create'
    | '/valoracion/create'
    | '/viajes/$codigoViaje'
    | '/taxi'
    | '/reservas'
    | '/valoracion'
    | '/viajes'
    | '/admin/conductor/$rut'
    | '/admin/reservas/$codigoReservaAdmin'
    | '/admin/reservas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ExamplePage'
    | '/RTMap'
    | '/ayuda'
    | '/contacto'
    | '/login'
    | '/registro'
    | '/sobre'
    | '/taxi/ruta'
    | '/admin/conductores'
    | '/admin/create-booking'
    | '/admin/dashboard'
    | '/admin/taxis'
    | '/reservas/$codigoReserva'
    | '/reservas/create'
    | '/valoracion/create'
    | '/viajes/$codigoViaje'
    | '/taxi'
    | '/reservas'
    | '/valoracion'
    | '/viajes'
    | '/admin/conductor/$rut'
    | '/admin/reservas/$codigoReservaAdmin'
    | '/admin/reservas'
  id:
    | '__root__'
    | '/'
    | '/ExamplePage'
    | '/RTMap'
    | '/ayuda'
    | '/contacto'
    | '/login'
    | '/registro'
    | '/sobre'
    | '/taxi/ruta'
    | '/admin/conductores'
    | '/admin/create-booking'
    | '/admin/dashboard'
    | '/admin/taxis'
    | '/reservas/$codigoReserva'
    | '/reservas/create'
    | '/valoracion/create'
    | '/viajes/$codigoViaje'
    | '/taxi/'
    | '/reservas/'
    | '/valoracion/'
    | '/viajes/'
    | '/admin/conductor/$rut'
    | '/admin/reservas/$codigoReservaAdmin'
    | '/admin/reservas/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ExamplePageRoute: typeof ExamplePageRoute
  RTMapLazyRoute: typeof RTMapLazyRoute
  AyudaLazyRoute: typeof AyudaLazyRoute
  ContactoLazyRoute: typeof ContactoLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  RegistroLazyRoute: typeof RegistroLazyRoute
  SobreLazyRoute: typeof SobreLazyRoute
  TaxiRutaRoute: typeof TaxiRutaRoute
  AdminConductoresLazyRoute: typeof AdminConductoresLazyRoute
  AdminCreateBookingLazyRoute: typeof AdminCreateBookingLazyRoute
  AdminDashboardLazyRoute: typeof AdminDashboardLazyRoute
  AdminTaxisLazyRoute: typeof AdminTaxisLazyRoute
  ReservasCodigoReservaLazyRoute: typeof ReservasCodigoReservaLazyRoute
  ReservasCreateLazyRoute: typeof ReservasCreateLazyRoute
  ValoracionCreateLazyRoute: typeof ValoracionCreateLazyRoute
  ViajesCodigoViajeLazyRoute: typeof ViajesCodigoViajeLazyRoute
  TaxiIndexRoute: typeof TaxiIndexRoute
  ReservasIndexLazyRoute: typeof ReservasIndexLazyRoute
  ValoracionIndexLazyRoute: typeof ValoracionIndexLazyRoute
  ViajesIndexLazyRoute: typeof ViajesIndexLazyRoute
  AdminConductorRutLazyRoute: typeof AdminConductorRutLazyRoute
  AdminReservasCodigoReservaAdminLazyRoute: typeof AdminReservasCodigoReservaAdminLazyRoute
  AdminReservasIndexLazyRoute: typeof AdminReservasIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ExamplePageRoute: ExamplePageRoute,
  RTMapLazyRoute: RTMapLazyRoute,
  AyudaLazyRoute: AyudaLazyRoute,
  ContactoLazyRoute: ContactoLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  RegistroLazyRoute: RegistroLazyRoute,
  SobreLazyRoute: SobreLazyRoute,
  TaxiRutaRoute: TaxiRutaRoute,
  AdminConductoresLazyRoute: AdminConductoresLazyRoute,
  AdminCreateBookingLazyRoute: AdminCreateBookingLazyRoute,
  AdminDashboardLazyRoute: AdminDashboardLazyRoute,
  AdminTaxisLazyRoute: AdminTaxisLazyRoute,
  ReservasCodigoReservaLazyRoute: ReservasCodigoReservaLazyRoute,
  ReservasCreateLazyRoute: ReservasCreateLazyRoute,
  ValoracionCreateLazyRoute: ValoracionCreateLazyRoute,
  ViajesCodigoViajeLazyRoute: ViajesCodigoViajeLazyRoute,
  TaxiIndexRoute: TaxiIndexRoute,
  ReservasIndexLazyRoute: ReservasIndexLazyRoute,
  ValoracionIndexLazyRoute: ValoracionIndexLazyRoute,
  ViajesIndexLazyRoute: ViajesIndexLazyRoute,
  AdminConductorRutLazyRoute: AdminConductorRutLazyRoute,
  AdminReservasCodigoReservaAdminLazyRoute:
    AdminReservasCodigoReservaAdminLazyRoute,
  AdminReservasIndexLazyRoute: AdminReservasIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/ExamplePage",
        "/RTMap",
        "/ayuda",
        "/contacto",
        "/login",
        "/registro",
        "/sobre",
        "/taxi/ruta",
        "/admin/conductores",
        "/admin/create-booking",
        "/admin/dashboard",
        "/admin/taxis",
        "/reservas/$codigoReserva",
        "/reservas/create",
        "/valoracion/create",
        "/viajes/$codigoViaje",
        "/taxi/",
        "/reservas/",
        "/valoracion/",
        "/viajes/",
        "/admin/conductor/$rut",
        "/admin/reservas/$codigoReservaAdmin",
        "/admin/reservas/"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/ExamplePage": {
      "filePath": "ExamplePage.jsx"
    },
    "/RTMap": {
      "filePath": "RTMap.lazy.jsx"
    },
    "/ayuda": {
      "filePath": "ayuda.lazy.jsx"
    },
    "/contacto": {
      "filePath": "contacto.lazy.jsx"
    },
    "/login": {
      "filePath": "login.lazy.jsx"
    },
    "/registro": {
      "filePath": "registro.lazy.jsx"
    },
    "/sobre": {
      "filePath": "sobre.lazy.jsx"
    },
    "/taxi/ruta": {
      "filePath": "taxi/ruta.jsx"
    },
    "/admin/conductores": {
      "filePath": "admin/conductores.lazy.jsx"
    },
    "/admin/create-booking": {
      "filePath": "admin/create-booking.lazy.jsx"
    },
    "/admin/dashboard": {
      "filePath": "admin/dashboard.lazy.jsx"
    },
    "/admin/taxis": {
      "filePath": "admin/taxis.lazy.jsx"
    },
    "/reservas/$codigoReserva": {
      "filePath": "reservas/$codigoReserva.lazy.jsx"
    },
    "/reservas/create": {
      "filePath": "reservas/create.lazy.jsx"
    },
    "/valoracion/create": {
      "filePath": "valoracion/create.lazy.jsx"
    },
    "/viajes/$codigoViaje": {
      "filePath": "viajes/$codigoViaje.lazy.jsx"
    },
    "/taxi/": {
      "filePath": "taxi/index.jsx"
    },
    "/reservas/": {
      "filePath": "reservas/index.lazy.jsx"
    },
    "/valoracion/": {
      "filePath": "valoracion/index.lazy.jsx"
    },
    "/viajes/": {
      "filePath": "viajes/index.lazy.jsx"
    },
    "/admin/conductor/$rut": {
      "filePath": "admin/conductor/$rut.lazy.jsx"
    },
    "/admin/reservas/$codigoReservaAdmin": {
      "filePath": "admin/reservas/$codigoReservaAdmin.lazy.jsx"
    },
    "/admin/reservas/": {
      "filePath": "admin/reservas/index.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
